// Datos de muestra: se usan como fallback cuando el BFF (/api/bays) todavía
// no responde, para que la pantalla de Bahías sea navegable sin backend.
// Quitar el fallback en useBays.ts cuando el endpoint esté disponible.
import type { Bay, BayOccupancySummary } from '../types/bay.types';

const now = Date.now();
const iso = (offsetMinutes: number) => new Date(now + offsetMinutes * 60_000).toISOString();

export const MOCK_BAYS: Bay[] = [
  { id: 'b1', code: '1', sector: 'Mecánica General', workshopId: 'w1', status: 'DISPONIBLE', freeSince: iso(-40), assignment: null },
  {
    id: 'b2',
    code: '2',
    sector: 'Mecánica General',
    workshopId: 'w1',
    status: 'OCUPADA',
    freeSince: null,
    assignment: {
      reservationId: 'r1',
      orderId: 'o1',
      orderFolio: 'TP-2026-01291',
      orderStatus: 'EN_REPARACION',
      plate: 'HJKL12',
      vehicleLabel: 'Chevrolet Sail LT 2021',
      customerName: 'María Torres',
      bodyType: 'SEDAN',
      startsAt: iso(-90),
      endsAt: iso(60),
      reservedBy: 'jefe.taller@tallerpro.cl',
      mechanicName: 'Luis Peña',
      progressPercent: 65,
    },
  },
  { id: 'b3', code: '3', sector: 'Mecánica General', workshopId: 'w1', status: 'DISPONIBLE', freeSince: iso(-10), assignment: null },
  {
    id: 'b4',
    code: '4',
    sector: 'Mecánica General',
    workshopId: 'w1',
    status: 'RESERVADA',
    freeSince: null,
    assignment: {
      reservationId: 'r2',
      orderId: 'o2',
      orderFolio: 'TP-2026-01293',
      orderStatus: 'RECEPCIONADA',
      plate: 'RTYU45',
      vehicleLabel: 'Toyota Yaris 2019',
      customerName: 'Pedro Salas',
      bodyType: 'SEDAN',
      startsAt: iso(45),
      endsAt: iso(180),
      reservedBy: 'jefe.taller@tallerpro.cl',
      mechanicName: null,
      progressPercent: null,
    },
  },
  {
    id: 'b5',
    code: '5',
    sector: 'Frenos y Suspensión',
    workshopId: 'w1',
    status: 'OCUPADA',
    freeSince: null,
    assignment: {
      reservationId: 'r3',
      orderId: 'o3',
      orderFolio: 'TP-2026-01288',
      orderStatus: 'EN_REPARACION',
      plate: 'LMNO33',
      vehicleLabel: 'Hyundai Accent 2020',
      customerName: 'Sebastián Vidal',
      bodyType: 'SUV',
      startsAt: iso(-30),
      endsAt: iso(90),
      reservedBy: 'mecanico@tallerpro.cl',
      mechanicName: 'Carla Muñoz',
      progressPercent: 30,
    },
  },
  { id: 'b6', code: '6', sector: 'Frenos y Suspensión', workshopId: 'w1', status: 'DISPONIBLE', freeSince: iso(-120), assignment: null },
  { id: 'b7', code: '7', sector: 'Frenos y Suspensión', workshopId: 'w1', status: 'DISPONIBLE', freeSince: iso(-5), assignment: null },
  {
    id: 'b8',
    code: '8',
    sector: 'Electricidad',
    workshopId: 'w1',
    status: 'RESERVADA',
    freeSince: null,
    assignment: {
      reservationId: 'r4',
      orderId: 'o4',
      orderFolio: 'TP-2026-01294',
      orderStatus: 'DIAGNOSTICADA',
      plate: 'QWER99',
      vehicleLabel: 'Suzuki Swift 2018',
      customerName: 'Camila Fuentes',
      bodyType: 'SUV',
      startsAt: iso(20),
      endsAt: iso(150),
      reservedBy: 'jefe.taller@tallerpro.cl',
      mechanicName: null,
      progressPercent: null,
    },
  },
  { id: 'b9', code: '9', sector: 'Electricidad', workshopId: 'w1', status: 'DISPONIBLE', freeSince: iso(-200), assignment: null },
];

export const MOCK_BAYS_SUMMARY: BayOccupancySummary = {
  total: MOCK_BAYS.length,
  disponibles: MOCK_BAYS.filter((b) => b.status === 'DISPONIBLE').length,
  reservadas: MOCK_BAYS.filter((b) => b.status === 'RESERVADA').length,
  ocupadas: MOCK_BAYS.filter((b) => b.status === 'OCUPADA').length,
  occupancyRate: Math.round(
    (MOCK_BAYS.filter((b) => b.status !== 'DISPONIBLE').length / MOCK_BAYS.length) * 100,
  ),
  nextReleaseAt: iso(60),
  nextReleaseBayCode: '2',
};
